using EntregasCorreio.Models;
using EntregasCorreio.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
//var token = "eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Mzc0NzA5NjgsImlzcyI6InRva2VuLXNlcnZpY2UiLCJleHAiOjE3Mzc1NTczNjgsImp0aSI6IjlhNTM0ZWU3LTVhMTQtNDMyMC05MjM2LWFmMzhhNmVhMWI2MSIsImFtYmllbnRlIjoiUFJPRFVDQU8iLCJwZmwiOiJQSiIsImlwIjoiMzQuMzQuMjM0LjEwNSwgMTkyLjE2OC4xLjEzMSIsImNhdCI6IkJ6MCIsImNhcnRhby1wb3N0YWdlbSI6eyJjb250cmF0byI6Ijk5MTI2MTAwODciLCJudW1lcm8iOiIwMDc3Nzc1NTAzIiwiZHIiOjc0LCJhcGlzIjpbeyJhcGkiOjI3fSx7ImFwaSI6MzR9LHsiYXBpIjozNX0seyJhcGkiOjM2fSx7ImFwaSI6Mzd9LHsiYXBpIjo0MX0seyJhcGkiOjc2fSx7ImFwaSI6Nzh9LHsiYXBpIjo4MH0seyJhcGkiOjgzfSx7ImFwaSI6ODd9LHsiYXBpIjo5M30seyJhcGkiOjU2Nn0seyJhcGkiOjU4Nn0seyJhcGkiOjU4N30seyJhcGkiOjYyMX0seyJhcGkiOjYyM31dfSwiaWQiOiIwMTUxMDM0NTAwMDE1OCIsImNucGoiOiIwMTUxMDM0NTAwMDE1OCJ9.ZHjvP6BkuONpTCVnVK0pX5A9ajk9x3-rUp08k7Vo9dJ8VhPoOnktyyipb2PnfXVBBYoz72mZPUyJ5E9PkBsG0I6mtE4vKa7Rn5O1f0BCh83eeENlqA2xY0kmRHeR8S4TVd1Hp8DD2KS7oZXKoVXOwuHyRGVlVVqp0XM-lY8RlE9Hgq3QnNHwZ0phbs7EV1DzhRbj6s944Ea3N1lMrhscFERF_Yo5vEs1g2MzwAqyJmysVRDwCqKzLdZfXLyICv7Ecc7-_LEcyv5ZASHtq_DXFZoRNFnGv39qnh60ZCEEEElTP03Yy2d63I9RyD7DDzAtf-VLTX3iXKw27MjuN-7TxA\\";
var token = "eyJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Mzc2NDE5NzgsImlzcyI6InRva2VuLXNlcnZpY2UiLCJleHAiOjE3Mzc3MjgzNzgsImp0aSI6IjIyY2M5NTAzLWZiMDMtNDkzMC05OGE4LTJlMWZmNTc1NmZlOCIsImFtYmllbnRlIjoiUFJPRFVDQU8iLCJwZmwiOiJQSiIsImlwIjoiMzQuOTYuNTAuMTM4LCAxOTIuMTY4LjEuMTMwIiwiY2F0IjoiQnowIiwiY2FydGFvLXBvc3RhZ2VtIjp7ImNvbnRyYXRvIjoiOTkxMjYxMDA4NyIsIm51bWVybyI6IjAwNzc3NzU1MDMiLCJkciI6NzQsImFwaXMiOlt7ImFwaSI6Mjd9LHsiYXBpIjozNH0seyJhcGkiOjM1fSx7ImFwaSI6MzZ9LHsiYXBpIjozN30seyJhcGkiOjQxfSx7ImFwaSI6NzZ9LHsiYXBpIjo3OH0seyJhcGkiOjgwfSx7ImFwaSI6ODN9LHsiYXBpIjo4N30seyJhcGkiOjkzfSx7ImFwaSI6NTY2fSx7ImFwaSI6NTg2fSx7ImFwaSI6NTg3fSx7ImFwaSI6NjIxfSx7ImFwaSI6NjIzfV19LCJpZCI6IjAxNTEwMzQ1MDAwMTU4IiwiY25waiI6IjAxNTEwMzQ1MDAwMTU4In0.vwlBUerkiJSrfwsBa81qibjKITmukH79TFYMLsK8vYOMrsyxaRmRt4Gxw5u9pdM_OeG1lVofFjFSj15haRIRJFAn_U8ITX73bnzpuOzlIpcBmWqy-55G6IcjFody8wSB1FJmoVQpLyMK3pcZKT9YPre3_g_4MfsQ8_ReTAF46T_nBKzCHhfvirs8Z6CKJb99xnHKLvf0mW2RHGYCRBbD_es9gkrInqT0i8R2SX8Jx382ZptdPtrmA52RWAIuOnf2vY0Z8OHQFO7AbJzUA63cyorPQRIscsGUviG-fFfM7-Rh7HAD7NwUEwT5SVCET_nApESfT2IUha5CKOunbdG1xw";

builder.Services.AddSingleton(token);

builder.Services.AddHttpClient();

builder.Services.AddScoped<FreteService>();

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
